apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "Geonorge.MinSide"
  tags:
  - "internal"
spec:
  type: "website"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
